### ISSUE TITLE
HTTP source application fails to bind

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-gemfire#8]
As a user, I'm trying a simple partition test with `gemfire` as the binder; though I'm able to successfully bootstrap multiple consumer instances, but the producer in this case `http` source application fails to bind.

**apps:**

```
java "-Dgemfire.locators=localhost[55221]" -jar /log-sink/target/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar --server.port=9003 --spring.cloud.stream.bindings.input.destination=something --spring.cloud.stream.bindings.input.group=meetupgrp --spring.cloud.stream.bindings.input.partitioned=true --spring.cloud.stream.instanceCount=2 --spring.cloud.stream.instanceIndex=0

java "-Dgemfire.locators=localhost[55221]" -jar /log-sink/target/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar --server.port=9004 --spring.cloud.stream.bindings.input.destination=something --spring.cloud.stream.bindings.input.group=meetupgrp --spring.cloud.stream.bindings.input.partitioned=true --spring.cloud.stream.instanceCount=2 --spring.cloud.stream.instanceIndex=1

java "-Dgemfire.locators=localhost[55221]" -jar /http-source/target/http-source-1.0.0.BUILD-SNAPSHOT-exec.jar --spring.cloud.stream.bindings.output.destination=something --server.port=9001 --spring.cloud.stream.bindings.output.partitionKeyExpression=payload --spring.cloud.stream.bindings.output.partitionCount=2 
```

**error:**

```
EASE.jar!/, jar:file:/Users/sanandan/CodeSpaces/nextgen/spring-cloud-stream-modules/http-source/target/http-source-1.0.0.BUILD-SNAPSHOT-exec.jar!/lib/json-20140107.jar!/, jar:file:/Users/sanandan/CodeSpaces/nextgen/spring-cloud-stream-modules/http-source/target/http-source-1.0.0.BUILD-SNAPSHOT-exec.jar!/lib/spring-core-4.2.4.RELEASE.jar!/, jar:file:/Users/sanandan/CodeSpaces/nextgen/spring-cloud-stream-modules/http-source/target/http-source-1.0.0.BUILD-SNAPSHOT-exec.jar!/lib/objenesis-2.1.jar!/, jar:file:/Users/sanandan/CodeSpaces/nextgen/spring-cloud-stream-modules/http-source/target/http-source-1.0.0.BUILD-SNAPSHOT-exec.jar!/lib/spring-boot-autoconfigure-1.3.2.RELEASE.jar!/]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
    ... 1 more
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalArgumentException: [Assertion failed] - this argument is required; it must not be null
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
    at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
    at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
    at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
    at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:852)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
    at org.springframework.cloud.stream.module.http.HttpSourceApplication.main(HttpSourceApplication.java:31)
    ... 6 more
Caused by: java.lang.IllegalArgumentException: [Assertion failed] - this argument is required; it must not be null
    at org.springframework.util.Assert.notNull(Assert.java:115)
    at org.springframework.util.Assert.notNull(Assert.java:126)
    at org.springframework.cloud.stream.binder.gemfire.SendingHandler.<init>(SendingHandler.java:154)
    at org.springframework.cloud.stream.binder.gemfire.GemfireMessageChannelBinder.bindProducer(GemfireMessageChannelBinder.java:309)
    at org.springframework.cloud.stream.binder.gemfire.GemfireMessageChannelBinder.bindProducer(GemfireMessageChannelBinder.java:60)
    at org.springframework.cloud.stream.binding.ChannelBindingService.bindProducer(ChannelBindingService.java:87)
    at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:266)
    at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:58)
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
    ... 20 more
```

**Comment by pperalta** [comment]
Fixed in df3d1de
